# Generated by Django 3.2.7 on 2021-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[('1', 'male'), ('2', 'female'), ('3', 'unknown')], default=1),
            preserve_default=False,
        ),
    ]
