# Generated by Django 3.2.7 on 2021-10-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_skype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='extraPhone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
