# Generated by Django 3.2.7 on 2021-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211002_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='spentaimes',
            field=models.TextField(blank=True),
        ),
    ]
