# Generated by Django 3.2.7 on 2021-10-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_spentaimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'unknown')], default='3', max_length=10),
        ),
    ]
