# Generated by Django 3.2.7 on 2021-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_position_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lastName',
            new_name='father_Name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surName',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
