# Generated by Django 3.2.7 on 2021-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211002_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'employee'), (1, 'teamlead'), (2, 'boss')], default='0', max_length=20),
        ),
    ]
