# Generated by Django 3.2.7 on 2021-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('0', 'employee'), ('1', 'teamlead'), ('2', 'boss')], default='0', max_length=20),
        ),
    ]
