# Generated by Django 3.2.7 on 2021-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admChanged',
            field=models.CharField(default='boss', max_length=50),
        ),
    ]
