# Generated by Django 3.2.7 on 2021-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_requesst'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesst',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
