# Generated by Django 3.2.7 on 2021-10-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_requesst_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesst',
            old_name='solved',
            new_name='approved',
        ),
    ]
