# Generated by Django 3.2.7 on 2021-10-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211002_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='finrequest',
            new_name='finance_request',
        ),
        migrations.RemoveField(
            model_name='vacation_request',
            name='price',
        ),
        migrations.AddField(
            model_name='vacation_request',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='sick_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(null=True)),
                ('last_date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
