# Generated by Django 3.2.7 on 2021-10-02 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211002_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='sick_request',
            name='case',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sick_request',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sick_request',
            name='worker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='long_sick_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(null=True)),
                ('last_date', models.DateField(null=True)),
                ('case', models.TextField(default='Заболел')),
                ('contact', models.IntegerField(null=True)),
                ('worker', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(upload_to='')),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
