# Generated by Django 3.2.7 on 2021-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_answer_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
