# Generated by Django 3.2.7 on 2021-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(default='Дистанционное мероприятие', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(default='iOS Разработка', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Выступление спикера', max_length=50),
        ),
    ]
