# Generated by Django 3.2.7 on 2021-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_prooffile_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prooffile',
        ),
    ]
