# Generated by Django 3.2.7 on 2021-10-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_delete_prooffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='todo',
        ),
    ]
