# Generated by Django 3.2.7 on 2021-10-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_text_task_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
